/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package editortexto;

import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultListModel;
import javax.swing.JTextArea;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

/**
 *
 * @author hu220
 */
public final class Fuente extends javax.swing.JFrame {

    int num;
    JTextArea caja;
    String contCaja;

    public Fuente(JTextArea caja) {
        initComponents();
        this.caja = caja;
        num = BlockDeNotas.getAux();
        tema(num);
        poblarListaTamano();
        poblarListaFuente();
        poblarListaEstilo();
    }

    public void tema(int num) {
        switch (num) {
            case 0:
                jPanel8.setBackground(new Color(230, 230, 230));
                jPanel3.setBackground(new Color(230, 230, 230));
                lblFuente.setForeground(new Color(0, 0, 0));
                lblEstilo.setForeground(new Color(0, 0, 0));
                lblTamano.setForeground(new Color(0, 0, 0));
                jScrollPane1.setBackground(new Color(255, 255, 255));
                jScrollPane2.setBackground(new Color(255, 255, 255));
                jScrollPane3.setBackground(new Color(255, 255, 255));
                jScrollPane4.setBackground(new Color(255, 255, 255));
                panelFondo.setBackground(new Color(230, 230, 230));
                panelFondo2.setBackground(new Color(230, 230, 230));
                panelEstilo.setBackground(new Color(255, 255, 255));
                panelFuente.setBackground(new Color(255, 255, 255));
                panelTamano.setBackground(new Color(255, 255, 255));
                listTamano.setForeground(new Color(0, 0, 0));
                listTamano.setBackground(new Color(255, 255, 255));
                listFuente.setForeground(new Color(0, 0, 0));
                listFuente.setBackground(new Color(255, 255, 255));
                listEstilo.setForeground(new Color(0, 0, 0));
                listEstilo.setBackground(new Color(255, 255, 255));
                jTextoMuestra.setForeground(new Color(0, 0, 0));
                jTextoMuestra.setBackground(new Color(230,230,230));
                break;
            case 1:
                jTextoMuestra.setBackground(new Color(0,0,0));
                lblFuente.setForeground(new Color(255, 255, 255));
                lblEstilo.setForeground(new Color(255, 255, 255));
                lblTamano.setForeground(new Color(255, 255, 255));
                jPanel8.setBackground(new Color(0, 0, 0));
                jPanel3.setBackground(new Color(0, 0, 0));
                jScrollPane1.setBackground(new Color(50, 50, 50));
                jScrollPane2.setBackground(new Color(50, 50, 50));
                jScrollPane3.setBackground(new Color(50, 50, 50));
                jScrollPane4.setBackground(new Color(50, 50, 50));
                panelFondo.setBackground(new Color(0, 0, 0));
                panelFondo2.setBackground(new Color(0, 0, 0));
                panelEstilo.setBackground(new Color(50, 50, 50));
                panelFuente.setBackground(new Color(50, 50, 50));
                panelTamano.setBackground(new Color(50, 50, 50));
                listTamano.setForeground(new Color(255, 255, 255));
                listTamano.setBackground(new Color(50, 50, 50));
                listFuente.setForeground(new Color(255, 255, 255));
                listFuente.setBackground(new Color(50, 50, 50));
                listEstilo.setForeground(new Color(255, 255, 255));
                listEstilo.setBackground(new Color(50, 50, 50));
                jTextoMuestra.setForeground(new Color(255, 255, 255));
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        panelFondo = new javax.swing.JPanel();
        panelFondo2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextoMuestra = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        lblFuente = new javax.swing.JLabel();
        lblEstilo = new javax.swing.JLabel();
        lblTamano = new javax.swing.JLabel();
        panelTamano = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listTamano = new javax.swing.JList<>();
        panelFuente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFuente = new javax.swing.JList<>();
        panelEstilo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEstilo = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Fuente");
        setResizable(false);

        panelFondo.setBackground(new java.awt.Color(255, 255, 255));

        panelFondo2.setBackground(new java.awt.Color(255, 255, 255));
        panelFondo2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jTextoMuestra.setColumns(20);
        jTextoMuestra.setRows(5);
        jTextoMuestra.setText("Este es un texto de muestra.");
        jScrollPane4.setViewportView(jTextoMuestra);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jButton3.setText("Aplicar");
        jButton3.setPreferredSize(new java.awt.Dimension(72, 23));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelFondo2Layout = new javax.swing.GroupLayout(panelFondo2);
        panelFondo2.setLayout(panelFondo2Layout);
        panelFondo2Layout.setHorizontalGroup(
            panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFondo2Layout.setVerticalGroup(
            panelFondo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelFondo2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lblFuente.setFont(new java.awt.Font("TeXGyreHeros", 1, 15)); // NOI18N
        lblFuente.setText("Fuente:");

        lblEstilo.setFont(new java.awt.Font("TeXGyreHeros", 1, 15)); // NOI18N
        lblEstilo.setText("Estilo:");

        lblTamano.setFont(new java.awt.Font("TeXGyreHeros", 1, 15)); // NOI18N
        lblTamano.setText("Tamaño:");

        panelTamano.setBackground(new java.awt.Color(255, 255, 255));
        panelTamano.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane3.setBorder(null);

        listTamano.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listTamano.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "22", "24", "26", "28", "30", "32", "34", "36", "40", "44", "48", "52", "56", "60", "64" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listTamano);

        javax.swing.GroupLayout panelTamanoLayout = new javax.swing.GroupLayout(panelTamano);
        panelTamano.setLayout(panelTamanoLayout);
        panelTamanoLayout.setHorizontalGroup(
            panelTamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
        );
        panelTamanoLayout.setVerticalGroup(
            panelTamanoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
        );

        panelFuente.setBackground(new java.awt.Color(255, 255, 255));
        panelFuente.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane1.setBorder(null);

        listFuente.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listFuente.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listFuente);

        javax.swing.GroupLayout panelFuenteLayout = new javax.swing.GroupLayout(panelFuente);
        panelFuente.setLayout(panelFuenteLayout);
        panelFuenteLayout.setHorizontalGroup(
            panelFuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );
        panelFuenteLayout.setVerticalGroup(
            panelFuenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        panelEstilo.setBackground(new java.awt.Color(255, 255, 255));
        panelEstilo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jScrollPane2.setBorder(null);

        listEstilo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        listEstilo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Cursiva", "Negrita", "", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listEstilo);

        javax.swing.GroupLayout panelEstiloLayout = new javax.swing.GroupLayout(panelEstilo);
        panelEstilo.setLayout(panelEstiloLayout);
        panelEstiloLayout.setHorizontalGroup(
            panelEstiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        panelEstiloLayout.setVerticalGroup(
            panelEstiloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelFondo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelFondoLayout.createSequentialGroup()
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelFuente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuente))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstilo)
                            .addComponent(panelEstilo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTamano)
                            .addComponent(panelTamano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuente)
                    .addComponent(lblEstilo)
                    .addComponent(lblTamano))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelTamano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelFuente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEstilo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelFondo, java.awt.BorderLayout.CENTER);

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poblarListaTamano() {
        // Lista de tamaños de letra
        String[] tamanos = {"8", "10", "12", "14", "16", "18", "20", "22", "24", "26", "28", "30", "32", "36", "40", "44", "48", "52", "56", "60", "64", "70", "76", "80", "86", "92", "100"};
        // Crear un modelo de lista para los tamaños
        DefaultListModel<String> modeloTamano = new DefaultListModel<>();
        for (String tamano : tamanos) {
            modeloTamano.addElement(tamano);
        }
        // Asignar el modelo a la lista de tamaño de letra
        listTamano.setModel(modeloTamano);
    }

    private void poblarListaFuente() {
        // Obtener todas las familias de fuentes disponibles
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] familias = ge.getAvailableFontFamilyNames();

        // Crear un modelo de lista para las fuentes
        DefaultListModel<String> modeloFuente = new DefaultListModel<>();
        for (String familia : familias) {
            modeloFuente.addElement(familia);
        }
        // Asignar el modelo a la lista de fuentes
        listFuente.setModel(modeloFuente);
    }

    private Font aplicarCambios(JTextArea caja) {
        // Obtener el tamaño de letra seleccionado
        int tamano = Integer.parseInt(listTamano.getSelectedValue());
        // Obtener la fuente seleccionada
        String fuente = listFuente.getSelectedValue();
        // Obtener el estilo seleccionado
        int estilo = listEstilo.getSelectedIndex();
        // Aplicar los cambios al JTextArea
        caja.setFont(new Font(fuente, estilo, tamano));
        return caja.getFont();
    }

    private void poblarListaEstilo() {
        // Lista de estilos
        String[] estilos = {"Normal", "Negrita", "Cursiva", "Negrita y Cursiva"};

        // Crear un modelo de lista para los estilos
        DefaultListModel<String> modeloEstilo = new DefaultListModel<>();
        for (String estilo : estilos) {
            modeloEstilo.addElement(estilo);
        }
        // Asignar el modelo a la lista de estilos
        listEstilo.setModel(modeloEstilo);
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

//    private void actualizarLineaMuestra() {
//        jTextoMuestra.setFont(aplicarCambios(jTextoMuestra));
//    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        caja.setFont(aplicarCambios(caja));
        this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextoMuestra;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblFuente;
    private javax.swing.JLabel lblTamano;
    private javax.swing.JList<String> listEstilo;
    private javax.swing.JList<String> listFuente;
    private javax.swing.JList<String> listTamano;
    private javax.swing.JPanel panelEstilo;
    private javax.swing.JPanel panelFondo;
    private javax.swing.JPanel panelFondo2;
    private javax.swing.JPanel panelFuente;
    private javax.swing.JPanel panelTamano;
    // End of variables declaration//GEN-END:variables

}
